### ISSUE TITLE
create rfc for @educational decorator

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio-rfcs#2]
We'd want this to:
- point to a production version (and add `See Also`)
- inject standard warning about using efficiency of educational code version production code
- inherit docstring from production version
- confirm signature is the same between the educational and production implementations

**Comment by wasade** [comment]
I think a critical item here is how the test code is handled as I think it would be useful to exercise the API independent of the implementation. The indirection done with biocore/scikit-bio#1040 probably isn't the best way to go about it, but it works for the moment. Specifically, I think we may want to do a single mixin base per method tested as opposed to having combined code (as is the case with `unweighted_unifrac` and `weighted_unifrac`). I suspect there is a common approach that can be taken with the test code which I believe would help to standardize the inclusion of different implementations of methods.

**Comment by gregcaporaso** [comment]
I agree that this is a key piece, and I agree that separating the tests out per method is a better way to go than what I did for the `*unifrac` tests.

**Comment by gregcaporaso** [comment]
We've decided that educational implementations are better suited for [IAB](http://www.readiab.org), which will also simplify scikit-bio. This will be revisited in the context of IAB (gregcaporaso/An-Introduction-to-Applied-Bioinformatics#180).
